### ISSUE TITLE
Unable to build on macOS with Xamarin 6.0.2

### ISSUE THREAD

**Issue by niemyjski** [adamped/XamarinForms.NetStandard#1]
```
Error: /Users/blake/Code/XamarinForms.NetStandard/XamarinForms.NetStandard/XamarinForms.NetStandard/XamarinForms.NetStandard.csproj: /Users/blake/Code/XamarinForms.NetStandard/XamarinForms.NetStandard/XamarinForms.NetStandard/XamarinForms.NetStandard.csproj could not import "$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets" (XamarinForms.NetStandard)
```

**Comment by adamped** [comment]
I removed an old Nuget reference as I looked over the project again. However I don't get the specific error you mentioned above. Try with the latest version and also do you have the latest stable version of Xamarin downloaded?

**Comment by adamped** [comment]
Closing due to no response. Feel free to comment again if you still have the issue.

**Comment by niemyjski** [comment]
Sorry, I still have this issue. Just missed the response to this issue.

**Comment by niemyjski** [comment]
I'm downloading the latest stable version now and will try again.

**Comment by niemyjski** [comment]
Error: /Users/blake/Code/XamarinForms.NetStandard/XamarinForms.NetStandard/XamarinForms.NetStandard/XamarinForms.NetStandard.csproj: /Users/blake/Code/XamarinForms.NetStandard/XamarinForms.NetStandard/XamarinForms.NetStandard/XamarinForms.NetStandard.csproj could not import "$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets" (XamarinForms.NetStandard)

<img width="1426" alt="screen shot 2016-08-18 at 9 17 43 am" src="https://cloud.githubusercontent.com/assets/1020579/17777061/aee771c2-6524-11e6-8de0-40c5157a57fa.png">
