### ISSUE TITLE
Are packages.config files still required?

### ISSUE THREAD

**Issue by tbaggett** [adamped/XamarinForms.NetStandard#2]
Hi Adam,

I'm still trying to work through the issues with converting my Xamarin.Forms library to NetStandard before posting in the forums about them, so I'm going through your example here from top to bottom to see if I've overlooked anything.

I see your project still has the packages.config files in the XamarinForms.NetStandard.Droid and ...iOS platform-specific app projects. I thought those wouldn't be used any longer, so I removed them from my project. Are they still supposed to be there?

https://github.com/adamped/XamarinForms.NetStandard/blob/master/XamarinForms.NetStandard/XamarinForms.NetStandard.Droid/packages.config

https://github.com/adamped/XamarinForms.NetStandard/blob/master/XamarinForms.NetStandard/XamarinForms.NetStandard.iOS/packages.config

I have removed the packages.config files from my local copy of your project and updated the version of Xamarin.Forms being used to v2.3.1.114, the latest stable release.

I'm doing development on a Mac running Parallels. I downloaded the prepackaged "Windows 10 Development Environment" VM image and updated the tools. I built your project in that environment in case my dev image is somehow misconfigured. It reports the build is successful, but I still get a "Build action 'EmbeddedResource' is not supplied by one or more of the project's targets.' message for each of the two Xaml files in your project.

I can create a PR and share the changes/updates I made to your project if you want to take a look.

**Comment by adamped** [comment]
The packages.config aren't required, I might have left them in the File System by mistake and git uploaded them. 

If you just provide a link to your fork on github I have a look.

**Comment by tbaggett** [comment]
Hi Adam, sorry it took so long to get this done! 

I've removed the unneeded packages.config files and outdated import statements in a couple of the csproj files in this [PR](https://github.com/adamped/XamarinForms.NetStandard/pull/3).

I verified all the targets are building and launching correctly. The only issue is I see this error reported for each of the xaml files in the portable library project:

Build action 'EmbeddedResource' is not supported by one or more of the project's targets.

I'm curious if you see this as well with these changes. Please let me know the results if you have time to try it.

**Comment by adamped** [comment]
It all builds nicely for me, thanks for removing the files. I still do get the Build Action errors but it still builds and runs as expected. However in my other netstandard proj I don't get these errors will have to look around and see what the difference is.
